apiVersion: v1
kind: ReplicationController   # kind表明此资源对象的类型，ReplicationController表示这是一个副本控制器 RC
metadata:
  name: mysql                 # RC的名称，全局唯一
spec:                         # 定义此资源对象的相关属性
  replicas: 1                 # Pod副本期待数量，此集群内始终有且只有一个Pod实例在运行
  selector:                   # Pod标签选择器，监控和管理这些标签的Pod实例
    app: mysql                # 符合目标的Pod拥有此标签
  template:                   # 模板，集群中Pod实例个数小于上面预设的replicas时，根据此模板启动新的Pod
    metadata:
      labels:                 # 此Pod的标签
        app: mysql            # Pod副本拥有的标签，必须严格对应上面RC的selector
    spec:
      containers:             # Pod容器的定义部分
      - name: mysql           # 容器名称
        image: mysql          # 容器对应的docker image
        ports:
        - containerPort: 3306 # 容器暴露的端口号
        env:                  # 注入到容器内的环境变量
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"