apiVersion: v1
kind: Service
metadata:
  name: myweb
spec:
  type: NodePort # 外网访问模式，在kubernetes集群外，可以通过30001端口访问此服务
  ports:
    - port: 8080 # 30001端口映射到kubernetes的8080端口上
      nodePort: 30001
  selector:
    app: myweb